#!/bin/sh
#
# Fix Broken Firewall Configuration
# Updates existing firewall to use proper custom rules
#

# Check if running as root
if [ "$(id -u)" -ne 0 ]; then
    echo "[X] Error: This script must be run as root"
    echo "    Run: sudo sh fix-firewall.sh"
    exit 1
fi

echo "================================================================"
echo "  Fixing Firewall Configuration"
echo "================================================================"
echo ""

# Get current SSH port
CURRENT_SSH_PORT=$(sockstat -l | grep sshd | grep -o ':\([0-9]*\)' | head -1 | cut -d: -f2)
if [ -z "$CURRENT_SSH_PORT" ]; then
    CURRENT_SSH_PORT="22"
fi

echo "[i] Detected SSH port: $CURRENT_SSH_PORT"
echo ""

# Get OPNsense IP or use 'any'
echo "Enter OPNsense IP address to restrict RADIUS access"
read -p "(or press Enter for 'any' to allow from anywhere): " OPNSENSE_IP

if [ -z "$OPNSENSE_IP" ] || [ "$OPNSENSE_IP" = "any" ]; then
    OPNSENSE_IP="any"
    RADIUS_AUTH_RULE="allow udp from any to me 1812 in keep-state"
    RADIUS_ACCT_RULE="allow udp from any to me 1813 in keep-state"
else
    RADIUS_AUTH_RULE="allow udp from $OPNSENSE_IP to me 1812 in keep-state"
    RADIUS_ACCT_RULE="allow udp from $OPNSENSE_IP to me 1813 in keep-state"
fi

echo ""
echo "[i] Creating custom firewall rules file..."
echo ""

# Create proper custom firewall rules file
cat > /etc/rc.firewall.local <<EOF
#!/bin/sh
#
# BoldVPN RADIUS Server - Custom Firewall Rules
# Auto-generated by fix-firewall.sh
#

# Define command shortcut
fwcmd="ipfw -q add"

# Flush existing rules
ipfw -q -f flush

# Rule 100: Allow all traffic on loopback interface
\$fwcmd 100 allow ip from any to any via lo0

# Rule 200-210: Prevent spoofing on loopback
\$fwcmd 200 deny ip from any to 127.0.0.0/8
\$fwcmd 210 deny ip from 127.0.0.0/8 to any

# Rule 300: Allow all established TCP connections
\$fwcmd 300 allow tcp from any to any established

# Rule 400: Allow SSH - CRITICAL!
\$fwcmd 400 allow tcp from any to me $CURRENT_SSH_PORT in keep-state
\$fwcmd 410 allow tcp from me $CURRENT_SSH_PORT to any out keep-state

# Rule 500-510: Allow RADIUS ports
\$fwcmd 500 $RADIUS_AUTH_RULE
\$fwcmd 510 $RADIUS_ACCT_RULE

# Rule 600-620: Allow future services
\$fwcmd 600 allow tcp from any to me 3000 in keep-state   # API
\$fwcmd 610 allow tcp from any to me 80 in keep-state     # HTTP
\$fwcmd 620 allow tcp from any to me 443 in keep-state    # HTTPS

# Rule 700: Allow all outgoing traffic
\$fwcmd 700 allow ip from me to any out keep-state

# Rule 800: Allow ICMP (ping, traceroute, etc.)
\$fwcmd 800 allow icmp from any to any

# Rule 65000: Deny and log everything else
\$fwcmd 65000 deny log ip from any to any

EOF

chmod 755 /etc/rc.firewall.local

echo "[OK] Custom firewall rules created at /etc/rc.firewall.local"
echo ""

# Show the rules that will be applied
echo "================================================================"
echo "  Firewall Rules Preview"
echo "================================================================"
echo ""
echo "Rule 100: Allow loopback"
echo "Rule 200: Block loopback spoofing"
echo "Rule 300: Allow established connections"
echo "Rule 400: Allow SSH on port $CURRENT_SSH_PORT            [CRITICAL]"
echo "Rule 500: Allow RADIUS auth (1812/udp)"
if [ "$OPNSENSE_IP" = "any" ]; then
    echo "          From: ANY IP"
else
    echo "          From: $OPNSENSE_IP only"
fi
echo "Rule 510: Allow RADIUS acct (1813/udp)"
if [ "$OPNSENSE_IP" = "any" ]; then
    echo "          From: ANY IP"
else
    echo "          From: $OPNSENSE_IP only"
fi
echo "Rule 600: Allow API (3000/tcp)"
echo "Rule 610: Allow HTTP (80/tcp)"
echo "Rule 620: Allow HTTPS (443/tcp)"
echo "Rule 700: Allow all outgoing"
echo "Rule 800: Allow ICMP (ping)"
echo "Rule 65000: Deny all others (logged)"
echo ""

# Update rc.conf to use custom script
echo "[i] Updating rc.conf to use custom firewall script..."
sysrc firewall_enable="YES"
sysrc firewall_script="/etc/rc.firewall.local"
sysrc firewall_logging="YES"

# Remove broken settings
sysrc -x firewall_type
sysrc -x firewall_myservices
sysrc -x firewall_allowservices

echo "[OK] rc.conf updated"
echo ""

# Ask for confirmation
echo "================================================================"
echo "  Ready to Apply Firewall Rules"
echo "================================================================"
echo ""
read -p "Apply these rules now? (yes/no): " CONFIRM

if [ "$CONFIRM" != "yes" ]; then
    echo ""
    echo "[!] Firewall rules saved but not applied"
    echo "    To apply later: service ipfw start"
    echo ""
    exit 0
fi

echo ""
echo "[i] Applying firewall rules..."

# Execute the custom rules script
/etc/rc.firewall.local

# Start/restart the firewall service
service ipfw restart 2>/dev/null || service ipfw start

echo ""
echo "================================================================"
echo "  [OK] Firewall Rules Applied!"
echo "================================================================"
echo ""

# Show active rules
echo "Active firewall rules:"
echo ""
ipfw list

echo ""
echo "================================================================"
echo "  [OK] Firewall Configuration Complete!"
echo "================================================================"
echo ""
echo "Allowed services:"
echo "  [OK] SSH on port $CURRENT_SSH_PORT"
echo "  [OK] RADIUS auth (1812/udp)"
if [ "$OPNSENSE_IP" != "any" ]; then
    echo "       Restricted to: $OPNSENSE_IP"
fi
echo "  [OK] RADIUS acct (1813/udp)"
echo "  [OK] API (3000/tcp)"
echo "  [OK] HTTP (80/tcp)"
echo "  [OK] HTTPS (443/tcp)"
echo ""
echo "Commands:"
echo "  View rules:    ipfw list"
echo "  Stop firewall: service ipfw stop"
echo "  Restart:       service ipfw restart"
echo ""
echo "[i] Test SSH in a new terminal to verify it works!"
echo ""


